/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public interface clangjavaConstants {
  public final static int CINDEX_VERSION_MAJOR = 0;
  public final static int CINDEX_VERSION_MINOR = 20;
  public final static int CINDEX_VERSION = (((0) *10000) +((20) *1));
  public final static String CINDEX_VERSION_STRING = "0.20";
}
