/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CX_CXXAccessSpecifier {
  CX_CXXInvalidAccessSpecifier,
  CX_CXXPublic,
  CX_CXXProtected,
  CX_CXXPrivate;

  public final int swigValue() {
    return swigValue;
  }

  public static CX_CXXAccessSpecifier swigToEnum(int swigValue) {
    CX_CXXAccessSpecifier[] swigValues = CX_CXXAccessSpecifier.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CX_CXXAccessSpecifier swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CX_CXXAccessSpecifier.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CX_CXXAccessSpecifier() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CX_CXXAccessSpecifier(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CX_CXXAccessSpecifier(CX_CXXAccessSpecifier swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

