/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXCallingConv {
  CXCallingConv_Default(0),
  CXCallingConv_C(1),
  CXCallingConv_X86StdCall(2),
  CXCallingConv_X86FastCall(3),
  CXCallingConv_X86ThisCall(4),
  CXCallingConv_X86Pascal(5),
  CXCallingConv_AAPCS(6),
  CXCallingConv_AAPCS_VFP(7),
  CXCallingConv_PnaclCall(8),
  CXCallingConv_IntelOclBicc(9),
  CXCallingConv_Invalid(100),
  CXCallingConv_Unexposed(200);

  public final int swigValue() {
    return swigValue;
  }

  public static CXCallingConv swigToEnum(int swigValue) {
    CXCallingConv[] swigValues = CXCallingConv.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXCallingConv swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXCallingConv.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXCallingConv() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXCallingConv(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXCallingConv(CXCallingConv swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

