/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXCompletionResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXCompletionResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXCompletionResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXCompletionResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCursorKind(CXCursorKind value) {
    clangjavaJNI.CXCompletionResult_CursorKind_set(swigCPtr, this, value.swigValue());
  }

  public CXCursorKind getCursorKind() {
    return CXCursorKind.swigToEnum(clangjavaJNI.CXCompletionResult_CursorKind_get(swigCPtr, this));
  }

  public void setCompletionString(SWIGTYPE_p_void value) {
    clangjavaJNI.CXCompletionResult_CompletionString_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCompletionString() {
    long cPtr = clangjavaJNI.CXCompletionResult_CompletionString_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public CXCompletionResult() {
    this(clangjavaJNI.new_CXCompletionResult(), true);
  }

}
