/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXCodeCompleteResults {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXCodeCompleteResults(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXCodeCompleteResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXCodeCompleteResults(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResults(CXCompletionResult value) {
    clangjavaJNI.CXCodeCompleteResults_Results_set(swigCPtr, this, CXCompletionResult.getCPtr(value), value);
  }

  public CXCompletionResult getResults() {
    long cPtr = clangjavaJNI.CXCodeCompleteResults_Results_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCompletionResult(cPtr, false);
  }

  public void setNumResults(long value) {
    clangjavaJNI.CXCodeCompleteResults_NumResults_set(swigCPtr, this, value);
  }

  public long getNumResults() {
    return clangjavaJNI.CXCodeCompleteResults_NumResults_get(swigCPtr, this);
  }

  public CXCodeCompleteResults() {
    this(clangjavaJNI.new_CXCodeCompleteResults(), true);
  }

}
