/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXCodeComplete_Flags {
  CXCodeComplete_IncludeMacros(0x01),
  CXCodeComplete_IncludeCodePatterns(0x02),
  CXCodeComplete_IncludeBriefComments(0x04);

  public final int swigValue() {
    return swigValue;
  }

  public static CXCodeComplete_Flags swigToEnum(int swigValue) {
    CXCodeComplete_Flags[] swigValues = CXCodeComplete_Flags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXCodeComplete_Flags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXCodeComplete_Flags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXCodeComplete_Flags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXCodeComplete_Flags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXCodeComplete_Flags(CXCodeComplete_Flags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

