/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXComment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXComment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXComment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXComment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setASTNode(SWIGTYPE_p_void value) {
    clangjavaJNI.CXComment_ASTNode_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getASTNode() {
    long cPtr = clangjavaJNI.CXComment_ASTNode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setTranslationUnit(SWIGTYPE_p_CXTranslationUnitImpl value) {
    clangjavaJNI.CXComment_TranslationUnit_set(swigCPtr, this, SWIGTYPE_p_CXTranslationUnitImpl.getCPtr(value));
  }

  public SWIGTYPE_p_CXTranslationUnitImpl getTranslationUnit() {
    long cPtr = clangjavaJNI.CXComment_TranslationUnit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CXTranslationUnitImpl(cPtr, false);
  }

  public CXComment() {
    this(clangjavaJNI.new_CXComment(), true);
  }

}
