/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXCompletionChunkKind {
  CXCompletionChunk_Optional,
  CXCompletionChunk_TypedText,
  CXCompletionChunk_Text,
  CXCompletionChunk_Placeholder,
  CXCompletionChunk_Informative,
  CXCompletionChunk_CurrentParameter,
  CXCompletionChunk_LeftParen,
  CXCompletionChunk_RightParen,
  CXCompletionChunk_LeftBracket,
  CXCompletionChunk_RightBracket,
  CXCompletionChunk_LeftBrace,
  CXCompletionChunk_RightBrace,
  CXCompletionChunk_LeftAngle,
  CXCompletionChunk_RightAngle,
  CXCompletionChunk_Comma,
  CXCompletionChunk_ResultType,
  CXCompletionChunk_Colon,
  CXCompletionChunk_SemiColon,
  CXCompletionChunk_Equal,
  CXCompletionChunk_HorizontalSpace,
  CXCompletionChunk_VerticalSpace;

  public final int swigValue() {
    return swigValue;
  }

  public static CXCompletionChunkKind swigToEnum(int swigValue) {
    CXCompletionChunkKind[] swigValues = CXCompletionChunkKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXCompletionChunkKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXCompletionChunkKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXCompletionChunkKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXCompletionChunkKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXCompletionChunkKind(CXCompletionChunkKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

