/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXCompletionContext {
  CXCompletionContext_Unexposed(0),
  CXCompletionContext_AnyType(1 << 0),
  CXCompletionContext_AnyValue(1 << 1),
  CXCompletionContext_ObjCObjectValue(1 << 2),
  CXCompletionContext_ObjCSelectorValue(1 << 3),
  CXCompletionContext_CXXClassTypeValue(1 << 4),
  CXCompletionContext_DotMemberAccess(1 << 5),
  CXCompletionContext_ArrowMemberAccess(1 << 6),
  CXCompletionContext_ObjCPropertyAccess(1 << 7),
  CXCompletionContext_EnumTag(1 << 8),
  CXCompletionContext_UnionTag(1 << 9),
  CXCompletionContext_StructTag(1 << 10),
  CXCompletionContext_ClassTag(1 << 11),
  CXCompletionContext_Namespace(1 << 12),
  CXCompletionContext_NestedNameSpecifier(1 << 13),
  CXCompletionContext_ObjCInterface(1 << 14),
  CXCompletionContext_ObjCProtocol(1 << 15),
  CXCompletionContext_ObjCCategory(1 << 16),
  CXCompletionContext_ObjCInstanceMessage(1 << 17),
  CXCompletionContext_ObjCClassMessage(1 << 18),
  CXCompletionContext_ObjCSelectorName(1 << 19),
  CXCompletionContext_MacroName(1 << 20),
  CXCompletionContext_NaturalLanguage(1 << 21),
  CXCompletionContext_Unknown(((1 << 22) -1));

  public final int swigValue() {
    return swigValue;
  }

  public static CXCompletionContext swigToEnum(int swigValue) {
    CXCompletionContext[] swigValues = CXCompletionContext.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXCompletionContext swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXCompletionContext.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXCompletionContext() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXCompletionContext(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXCompletionContext(CXCompletionContext swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

