/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXCommentInlineCommandRenderKind {
  CXCommentInlineCommandRenderKind_Normal,
  CXCommentInlineCommandRenderKind_Bold,
  CXCommentInlineCommandRenderKind_Monospaced,
  CXCommentInlineCommandRenderKind_Emphasized;

  public final int swigValue() {
    return swigValue;
  }

  public static CXCommentInlineCommandRenderKind swigToEnum(int swigValue) {
    CXCommentInlineCommandRenderKind[] swigValues = CXCommentInlineCommandRenderKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXCommentInlineCommandRenderKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXCommentInlineCommandRenderKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXCommentInlineCommandRenderKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXCommentInlineCommandRenderKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXCommentInlineCommandRenderKind(CXCommentInlineCommandRenderKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

