/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXCursorAndRangeVisitor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXCursorAndRangeVisitor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXCursorAndRangeVisitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXCursorAndRangeVisitor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setContext(SWIGTYPE_p_void value) {
    clangjavaJNI.CXCursorAndRangeVisitor_context_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getContext() {
    long cPtr = clangjavaJNI.CXCursorAndRangeVisitor_context_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setVisit(SWIGTYPE_p_f_p_void_CXCursor_CXSourceRange__CXVisitorResult value) {
    clangjavaJNI.CXCursorAndRangeVisitor_visit_set(swigCPtr, this, SWIGTYPE_p_f_p_void_CXCursor_CXSourceRange__CXVisitorResult.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_CXCursor_CXSourceRange__CXVisitorResult getVisit() {
    long cPtr = clangjavaJNI.CXCursorAndRangeVisitor_visit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_CXCursor_CXSourceRange__CXVisitorResult(cPtr, false);
  }

  public CXCursorAndRangeVisitor() {
    this(clangjavaJNI.new_CXCursorAndRangeVisitor(), true);
  }

}
