/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXCursor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXCursor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXCursor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXCursor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(CXCursorKind value) {
    clangjavaJNI.CXCursor_kind_set(swigCPtr, this, value.swigValue());
  }

  public CXCursorKind getKind() {
    return CXCursorKind.swigToEnum(clangjavaJNI.CXCursor_kind_get(swigCPtr, this));
  }

  public void setXdata(int value) {
    clangjavaJNI.CXCursor_xdata_set(swigCPtr, this, value);
  }

  public int getXdata() {
    return clangjavaJNI.CXCursor_xdata_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_p_void value) {
    clangjavaJNI.CXCursor_data_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getData() {
    long cPtr = clangjavaJNI.CXCursor_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public CXCursor() {
    this(clangjavaJNI.new_CXCursor(), true);
  }

}
