/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXDiagnosticDisplayOptions {
  CXDiagnostic_DisplaySourceLocation(0x01),
  CXDiagnostic_DisplayColumn(0x02),
  CXDiagnostic_DisplaySourceRanges(0x04),
  CXDiagnostic_DisplayOption(0x08),
  CXDiagnostic_DisplayCategoryId(0x10),
  CXDiagnostic_DisplayCategoryName(0x20);

  public final int swigValue() {
    return swigValue;
  }

  public static CXDiagnosticDisplayOptions swigToEnum(int swigValue) {
    CXDiagnosticDisplayOptions[] swigValues = CXDiagnosticDisplayOptions.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXDiagnosticDisplayOptions swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXDiagnosticDisplayOptions.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXDiagnosticDisplayOptions() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXDiagnosticDisplayOptions(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXDiagnosticDisplayOptions(CXDiagnosticDisplayOptions swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

