/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXFile_p {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXFile_p(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXFile_p obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXFile_p(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CXFile_p() {
    this(clangjavaJNI.new_CXFile_p(), true);
  }

  public void assign(SWIGTYPE_p_void value) {
    clangjavaJNI.CXFile_p_assign(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void value() {
    long cPtr = clangjavaJNI.CXFile_p_value(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_p_void cast() {
    long cPtr = clangjavaJNI.CXFile_p_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public static CXFile_p frompointer(SWIGTYPE_p_p_void t) {
    long cPtr = clangjavaJNI.CXFile_p_frompointer(SWIGTYPE_p_p_void.getCPtr(t));
    return (cPtr == 0) ? null : new CXFile_p(cPtr, false);
  }

}
