/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXGlobalOptFlags {
  CXGlobalOpt_None(0x0),
  CXGlobalOpt_ThreadBackgroundPriorityForIndexing(0x1),
  CXGlobalOpt_ThreadBackgroundPriorityForEditing(0x2),
  CXGlobalOpt_ThreadBackgroundPriorityForAll(clangjavaJNI.CXGlobalOpt_ThreadBackgroundPriorityForAll_get());

  public final int swigValue() {
    return swigValue;
  }

  public static CXGlobalOptFlags swigToEnum(int swigValue) {
    CXGlobalOptFlags[] swigValues = CXGlobalOptFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXGlobalOptFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXGlobalOptFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXGlobalOptFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXGlobalOptFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXGlobalOptFlags(CXGlobalOptFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

