/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxIncludedFileInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxIncludedFileInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxIncludedFileInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxIncludedFileInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHashLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxIncludedFileInfo_hashLoc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getHashLoc() {
    long cPtr = clangjavaJNI.CXIdxIncludedFileInfo_hashLoc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public void setFilename(String value) {
    clangjavaJNI.CXIdxIncludedFileInfo_filename_set(swigCPtr, this, value);
  }

  public String getFilename() {
    return clangjavaJNI.CXIdxIncludedFileInfo_filename_get(swigCPtr, this);
  }

  public void setFile(SWIGTYPE_p_void value) {
    clangjavaJNI.CXIdxIncludedFileInfo_file_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getFile() {
    long cPtr = clangjavaJNI.CXIdxIncludedFileInfo_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setIsImport(int value) {
    clangjavaJNI.CXIdxIncludedFileInfo_isImport_set(swigCPtr, this, value);
  }

  public int getIsImport() {
    return clangjavaJNI.CXIdxIncludedFileInfo_isImport_get(swigCPtr, this);
  }

  public void setIsAngled(int value) {
    clangjavaJNI.CXIdxIncludedFileInfo_isAngled_set(swigCPtr, this, value);
  }

  public int getIsAngled() {
    return clangjavaJNI.CXIdxIncludedFileInfo_isAngled_get(swigCPtr, this);
  }

  public void setIsModuleImport(int value) {
    clangjavaJNI.CXIdxIncludedFileInfo_isModuleImport_set(swigCPtr, this, value);
  }

  public int getIsModuleImport() {
    return clangjavaJNI.CXIdxIncludedFileInfo_isModuleImport_get(swigCPtr, this);
  }

  public CXIdxIncludedFileInfo() {
    this(clangjavaJNI.new_CXIdxIncludedFileInfo(), true);
  }

}
