/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXIdxDeclInfoFlags {
  CXIdxDeclFlag_Skipped(0x1);

  public final int swigValue() {
    return swigValue;
  }

  public static CXIdxDeclInfoFlags swigToEnum(int swigValue) {
    CXIdxDeclInfoFlags[] swigValues = CXIdxDeclInfoFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXIdxDeclInfoFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXIdxDeclInfoFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXIdxDeclInfoFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXIdxDeclInfoFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXIdxDeclInfoFlags(CXIdxDeclInfoFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

