/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXIdxAttrKind {
  CXIdxAttr_Unexposed(0),
  CXIdxAttr_IBAction(1),
  CXIdxAttr_IBOutlet(2),
  CXIdxAttr_IBOutletCollection(3);

  public final int swigValue() {
    return swigValue;
  }

  public static CXIdxAttrKind swigToEnum(int swigValue) {
    CXIdxAttrKind[] swigValues = CXIdxAttrKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXIdxAttrKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXIdxAttrKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXIdxAttrKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXIdxAttrKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXIdxAttrKind(CXIdxAttrKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

