/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxAttrInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxAttrInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxAttrInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxAttrInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(CXIdxAttrKind value) {
    clangjavaJNI.CXIdxAttrInfo_kind_set(swigCPtr, this, value.swigValue());
  }

  public CXIdxAttrKind getKind() {
    return CXIdxAttrKind.swigToEnum(clangjavaJNI.CXIdxAttrInfo_kind_get(swigCPtr, this));
  }

  public void setCursor(CXCursor value) {
    clangjavaJNI.CXIdxAttrInfo_cursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getCursor() {
    long cPtr = clangjavaJNI.CXIdxAttrInfo_cursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public void setLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxAttrInfo_loc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getLoc() {
    long cPtr = clangjavaJNI.CXIdxAttrInfo_loc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public CXIdxAttrInfo() {
    this(clangjavaJNI.new_CXIdxAttrInfo(), true);
  }

}
