/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxDeclInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxDeclInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxDeclInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxDeclInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEntityInfo(CXIdxEntityInfo value) {
    clangjavaJNI.CXIdxDeclInfo_entityInfo_set(swigCPtr, this, CXIdxEntityInfo.getCPtr(value), value);
  }

  public CXIdxEntityInfo getEntityInfo() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_entityInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxEntityInfo(cPtr, false);
  }

  public void setCursor(CXCursor value) {
    clangjavaJNI.CXIdxDeclInfo_cursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getCursor() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_cursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public void setLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxDeclInfo_loc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getLoc() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_loc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public void setSemanticContainer(CXIdxContainerInfo value) {
    clangjavaJNI.CXIdxDeclInfo_semanticContainer_set(swigCPtr, this, CXIdxContainerInfo.getCPtr(value), value);
  }

  public CXIdxContainerInfo getSemanticContainer() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_semanticContainer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxContainerInfo(cPtr, false);
  }

  public void setLexicalContainer(CXIdxContainerInfo value) {
    clangjavaJNI.CXIdxDeclInfo_lexicalContainer_set(swigCPtr, this, CXIdxContainerInfo.getCPtr(value), value);
  }

  public CXIdxContainerInfo getLexicalContainer() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_lexicalContainer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxContainerInfo(cPtr, false);
  }

  public void setIsRedeclaration(int value) {
    clangjavaJNI.CXIdxDeclInfo_isRedeclaration_set(swigCPtr, this, value);
  }

  public int getIsRedeclaration() {
    return clangjavaJNI.CXIdxDeclInfo_isRedeclaration_get(swigCPtr, this);
  }

  public void setIsDefinition(int value) {
    clangjavaJNI.CXIdxDeclInfo_isDefinition_set(swigCPtr, this, value);
  }

  public int getIsDefinition() {
    return clangjavaJNI.CXIdxDeclInfo_isDefinition_get(swigCPtr, this);
  }

  public void setIsContainer(int value) {
    clangjavaJNI.CXIdxDeclInfo_isContainer_set(swigCPtr, this, value);
  }

  public int getIsContainer() {
    return clangjavaJNI.CXIdxDeclInfo_isContainer_get(swigCPtr, this);
  }

  public void setDeclAsContainer(CXIdxContainerInfo value) {
    clangjavaJNI.CXIdxDeclInfo_declAsContainer_set(swigCPtr, this, CXIdxContainerInfo.getCPtr(value), value);
  }

  public CXIdxContainerInfo getDeclAsContainer() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_declAsContainer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxContainerInfo(cPtr, false);
  }

  public void setIsImplicit(int value) {
    clangjavaJNI.CXIdxDeclInfo_isImplicit_set(swigCPtr, this, value);
  }

  public int getIsImplicit() {
    return clangjavaJNI.CXIdxDeclInfo_isImplicit_get(swigCPtr, this);
  }

  public void setAttributes(SWIGTYPE_p_p_CXIdxAttrInfo value) {
    clangjavaJNI.CXIdxDeclInfo_attributes_set(swigCPtr, this, SWIGTYPE_p_p_CXIdxAttrInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p_CXIdxAttrInfo getAttributes() {
    long cPtr = clangjavaJNI.CXIdxDeclInfo_attributes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_CXIdxAttrInfo(cPtr, false);
  }

  public void setNumAttributes(long value) {
    clangjavaJNI.CXIdxDeclInfo_numAttributes_set(swigCPtr, this, value);
  }

  public long getNumAttributes() {
    return clangjavaJNI.CXIdxDeclInfo_numAttributes_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    clangjavaJNI.CXIdxDeclInfo_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return clangjavaJNI.CXIdxDeclInfo_flags_get(swigCPtr, this);
  }

  public CXIdxDeclInfo() {
    this(clangjavaJNI.new_CXIdxDeclInfo(), true);
  }

}
