/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxObjCContainerDeclInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxObjCContainerDeclInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxObjCContainerDeclInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxObjCContainerDeclInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeclInfo(CXIdxDeclInfo value) {
    clangjavaJNI.CXIdxObjCContainerDeclInfo_declInfo_set(swigCPtr, this, CXIdxDeclInfo.getCPtr(value), value);
  }

  public CXIdxDeclInfo getDeclInfo() {
    long cPtr = clangjavaJNI.CXIdxObjCContainerDeclInfo_declInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxDeclInfo(cPtr, false);
  }

  public void setKind(CXIdxObjCContainerKind value) {
    clangjavaJNI.CXIdxObjCContainerDeclInfo_kind_set(swigCPtr, this, value.swigValue());
  }

  public CXIdxObjCContainerKind getKind() {
    return CXIdxObjCContainerKind.swigToEnum(clangjavaJNI.CXIdxObjCContainerDeclInfo_kind_get(swigCPtr, this));
  }

  public CXIdxObjCContainerDeclInfo() {
    this(clangjavaJNI.new_CXIdxObjCContainerDeclInfo(), true);
  }

}
