/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxObjCProtocolRefListInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxObjCProtocolRefListInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxObjCProtocolRefListInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxObjCProtocolRefListInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProtocols(SWIGTYPE_p_p_CXIdxObjCProtocolRefInfo value) {
    clangjavaJNI.CXIdxObjCProtocolRefListInfo_protocols_set(swigCPtr, this, SWIGTYPE_p_p_CXIdxObjCProtocolRefInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p_CXIdxObjCProtocolRefInfo getProtocols() {
    long cPtr = clangjavaJNI.CXIdxObjCProtocolRefListInfo_protocols_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_CXIdxObjCProtocolRefInfo(cPtr, false);
  }

  public void setNumProtocols(long value) {
    clangjavaJNI.CXIdxObjCProtocolRefListInfo_numProtocols_set(swigCPtr, this, value);
  }

  public long getNumProtocols() {
    return clangjavaJNI.CXIdxObjCProtocolRefListInfo_numProtocols_get(swigCPtr, this);
  }

  public CXIdxObjCProtocolRefListInfo() {
    this(clangjavaJNI.new_CXIdxObjCProtocolRefListInfo(), true);
  }

}
