/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxContainerInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxContainerInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxContainerInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxContainerInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCursor(CXCursor value) {
    clangjavaJNI.CXIdxContainerInfo_cursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getCursor() {
    long cPtr = clangjavaJNI.CXIdxContainerInfo_cursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public CXIdxContainerInfo() {
    this(clangjavaJNI.new_CXIdxContainerInfo(), true);
  }

}
