/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxIBOutletCollectionAttrInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxIBOutletCollectionAttrInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxIBOutletCollectionAttrInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxIBOutletCollectionAttrInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttrInfo(CXIdxAttrInfo value) {
    clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_attrInfo_set(swigCPtr, this, CXIdxAttrInfo.getCPtr(value), value);
  }

  public CXIdxAttrInfo getAttrInfo() {
    long cPtr = clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_attrInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxAttrInfo(cPtr, false);
  }

  public void setObjcClass(CXIdxEntityInfo value) {
    clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_objcClass_set(swigCPtr, this, CXIdxEntityInfo.getCPtr(value), value);
  }

  public CXIdxEntityInfo getObjcClass() {
    long cPtr = clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_objcClass_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxEntityInfo(cPtr, false);
  }

  public void setClassCursor(CXCursor value) {
    clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_classCursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getClassCursor() {
    long cPtr = clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_classCursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public void setClassLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_classLoc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getClassLoc() {
    long cPtr = clangjavaJNI.CXIdxIBOutletCollectionAttrInfo_classLoc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public CXIdxIBOutletCollectionAttrInfo() {
    this(clangjavaJNI.new_CXIdxIBOutletCollectionAttrInfo(), true);
  }

}
