/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxImportedASTFileInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxImportedASTFileInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxImportedASTFileInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxImportedASTFileInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFile(SWIGTYPE_p_void value) {
    clangjavaJNI.CXIdxImportedASTFileInfo_file_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getFile() {
    long cPtr = clangjavaJNI.CXIdxImportedASTFileInfo_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setModule(SWIGTYPE_p_void value) {
    clangjavaJNI.CXIdxImportedASTFileInfo_module_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getModule() {
    long cPtr = clangjavaJNI.CXIdxImportedASTFileInfo_module_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxImportedASTFileInfo_loc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getLoc() {
    long cPtr = clangjavaJNI.CXIdxImportedASTFileInfo_loc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public void setIsImplicit(int value) {
    clangjavaJNI.CXIdxImportedASTFileInfo_isImplicit_set(swigCPtr, this, value);
  }

  public int getIsImplicit() {
    return clangjavaJNI.CXIdxImportedASTFileInfo_isImplicit_get(swigCPtr, this);
  }

  public CXIdxImportedASTFileInfo() {
    this(clangjavaJNI.new_CXIdxImportedASTFileInfo(), true);
  }

}
