/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXIdxEntityKind {
  CXIdxEntity_Unexposed(0),
  CXIdxEntity_Typedef(1),
  CXIdxEntity_Function(2),
  CXIdxEntity_Variable(3),
  CXIdxEntity_Field(4),
  CXIdxEntity_EnumConstant(5),
  CXIdxEntity_ObjCClass(6),
  CXIdxEntity_ObjCProtocol(7),
  CXIdxEntity_ObjCCategory(8),
  CXIdxEntity_ObjCInstanceMethod(9),
  CXIdxEntity_ObjCClassMethod(10),
  CXIdxEntity_ObjCProperty(11),
  CXIdxEntity_ObjCIvar(12),
  CXIdxEntity_Enum(13),
  CXIdxEntity_Struct(14),
  CXIdxEntity_Union(15),
  CXIdxEntity_CXXClass(16),
  CXIdxEntity_CXXNamespace(17),
  CXIdxEntity_CXXNamespaceAlias(18),
  CXIdxEntity_CXXStaticVariable(19),
  CXIdxEntity_CXXStaticMethod(20),
  CXIdxEntity_CXXInstanceMethod(21),
  CXIdxEntity_CXXConstructor(22),
  CXIdxEntity_CXXDestructor(23),
  CXIdxEntity_CXXConversionFunction(24),
  CXIdxEntity_CXXTypeAlias(25),
  CXIdxEntity_CXXInterface(26);

  public final int swigValue() {
    return swigValue;
  }

  public static CXIdxEntityKind swigToEnum(int swigValue) {
    CXIdxEntityKind[] swigValues = CXIdxEntityKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXIdxEntityKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXIdxEntityKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXIdxEntityKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXIdxEntityKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXIdxEntityKind(CXIdxEntityKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

