/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxEntityInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxEntityInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxEntityInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxEntityInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKind(CXIdxEntityKind value) {
    clangjavaJNI.CXIdxEntityInfo_kind_set(swigCPtr, this, value.swigValue());
  }

  public CXIdxEntityKind getKind() {
    return CXIdxEntityKind.swigToEnum(clangjavaJNI.CXIdxEntityInfo_kind_get(swigCPtr, this));
  }

  public void setTemplateKind(CXIdxEntityCXXTemplateKind value) {
    clangjavaJNI.CXIdxEntityInfo_templateKind_set(swigCPtr, this, value.swigValue());
  }

  public CXIdxEntityCXXTemplateKind getTemplateKind() {
    return CXIdxEntityCXXTemplateKind.swigToEnum(clangjavaJNI.CXIdxEntityInfo_templateKind_get(swigCPtr, this));
  }

  public void setLang(CXIdxEntityLanguage value) {
    clangjavaJNI.CXIdxEntityInfo_lang_set(swigCPtr, this, value.swigValue());
  }

  public CXIdxEntityLanguage getLang() {
    return CXIdxEntityLanguage.swigToEnum(clangjavaJNI.CXIdxEntityInfo_lang_get(swigCPtr, this));
  }

  public void setName(String value) {
    clangjavaJNI.CXIdxEntityInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return clangjavaJNI.CXIdxEntityInfo_name_get(swigCPtr, this);
  }

  public void setUSR(String value) {
    clangjavaJNI.CXIdxEntityInfo_USR_set(swigCPtr, this, value);
  }

  public String getUSR() {
    return clangjavaJNI.CXIdxEntityInfo_USR_get(swigCPtr, this);
  }

  public void setCursor(CXCursor value) {
    clangjavaJNI.CXIdxEntityInfo_cursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getCursor() {
    long cPtr = clangjavaJNI.CXIdxEntityInfo_cursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public void setAttributes(SWIGTYPE_p_p_CXIdxAttrInfo value) {
    clangjavaJNI.CXIdxEntityInfo_attributes_set(swigCPtr, this, SWIGTYPE_p_p_CXIdxAttrInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p_CXIdxAttrInfo getAttributes() {
    long cPtr = clangjavaJNI.CXIdxEntityInfo_attributes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_CXIdxAttrInfo(cPtr, false);
  }

  public void setNumAttributes(long value) {
    clangjavaJNI.CXIdxEntityInfo_numAttributes_set(swigCPtr, this, value);
  }

  public long getNumAttributes() {
    return clangjavaJNI.CXIdxEntityInfo_numAttributes_get(swigCPtr, this);
  }

  public CXIdxEntityInfo() {
    this(clangjavaJNI.new_CXIdxEntityInfo(), true);
  }

}
