/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxObjCCategoryDeclInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxObjCCategoryDeclInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxObjCCategoryDeclInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxObjCCategoryDeclInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setContainerInfo(CXIdxObjCContainerDeclInfo value) {
    clangjavaJNI.CXIdxObjCCategoryDeclInfo_containerInfo_set(swigCPtr, this, CXIdxObjCContainerDeclInfo.getCPtr(value), value);
  }

  public CXIdxObjCContainerDeclInfo getContainerInfo() {
    long cPtr = clangjavaJNI.CXIdxObjCCategoryDeclInfo_containerInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxObjCContainerDeclInfo(cPtr, false);
  }

  public void setObjcClass(CXIdxEntityInfo value) {
    clangjavaJNI.CXIdxObjCCategoryDeclInfo_objcClass_set(swigCPtr, this, CXIdxEntityInfo.getCPtr(value), value);
  }

  public CXIdxEntityInfo getObjcClass() {
    long cPtr = clangjavaJNI.CXIdxObjCCategoryDeclInfo_objcClass_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxEntityInfo(cPtr, false);
  }

  public void setClassCursor(CXCursor value) {
    clangjavaJNI.CXIdxObjCCategoryDeclInfo_classCursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getClassCursor() {
    long cPtr = clangjavaJNI.CXIdxObjCCategoryDeclInfo_classCursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public void setClassLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxObjCCategoryDeclInfo_classLoc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getClassLoc() {
    long cPtr = clangjavaJNI.CXIdxObjCCategoryDeclInfo_classLoc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public void setProtocols(CXIdxObjCProtocolRefListInfo value) {
    clangjavaJNI.CXIdxObjCCategoryDeclInfo_protocols_set(swigCPtr, this, CXIdxObjCProtocolRefListInfo.getCPtr(value), value);
  }

  public CXIdxObjCProtocolRefListInfo getProtocols() {
    long cPtr = clangjavaJNI.CXIdxObjCCategoryDeclInfo_protocols_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxObjCProtocolRefListInfo(cPtr, false);
  }

  public CXIdxObjCCategoryDeclInfo() {
    this(clangjavaJNI.new_CXIdxObjCCategoryDeclInfo(), true);
  }

}
