/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxBaseClassInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxBaseClassInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxBaseClassInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxBaseClassInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBase(CXIdxEntityInfo value) {
    clangjavaJNI.CXIdxBaseClassInfo_base_set(swigCPtr, this, CXIdxEntityInfo.getCPtr(value), value);
  }

  public CXIdxEntityInfo getBase() {
    long cPtr = clangjavaJNI.CXIdxBaseClassInfo_base_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxEntityInfo(cPtr, false);
  }

  public void setCursor(CXCursor value) {
    clangjavaJNI.CXIdxBaseClassInfo_cursor_set(swigCPtr, this, CXCursor.getCPtr(value), value);
  }

  public CXCursor getCursor() {
    long cPtr = clangjavaJNI.CXIdxBaseClassInfo_cursor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXCursor(cPtr, false);
  }

  public void setLoc(CXIdxLoc value) {
    clangjavaJNI.CXIdxBaseClassInfo_loc_set(swigCPtr, this, CXIdxLoc.getCPtr(value), value);
  }

  public CXIdxLoc getLoc() {
    long cPtr = clangjavaJNI.CXIdxBaseClassInfo_loc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxLoc(cPtr, false);
  }

  public CXIdxBaseClassInfo() {
    this(clangjavaJNI.new_CXIdxBaseClassInfo(), true);
  }

}
