/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXIdxObjCPropertyDeclInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXIdxObjCPropertyDeclInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXIdxObjCPropertyDeclInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXIdxObjCPropertyDeclInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDeclInfo(CXIdxDeclInfo value) {
    clangjavaJNI.CXIdxObjCPropertyDeclInfo_declInfo_set(swigCPtr, this, CXIdxDeclInfo.getCPtr(value), value);
  }

  public CXIdxDeclInfo getDeclInfo() {
    long cPtr = clangjavaJNI.CXIdxObjCPropertyDeclInfo_declInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxDeclInfo(cPtr, false);
  }

  public void setGetter(CXIdxEntityInfo value) {
    clangjavaJNI.CXIdxObjCPropertyDeclInfo_getter_set(swigCPtr, this, CXIdxEntityInfo.getCPtr(value), value);
  }

  public CXIdxEntityInfo getGetter() {
    long cPtr = clangjavaJNI.CXIdxObjCPropertyDeclInfo_getter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxEntityInfo(cPtr, false);
  }

  public void setSetter(CXIdxEntityInfo value) {
    clangjavaJNI.CXIdxObjCPropertyDeclInfo_setter_set(swigCPtr, this, CXIdxEntityInfo.getCPtr(value), value);
  }

  public CXIdxEntityInfo getSetter() {
    long cPtr = clangjavaJNI.CXIdxObjCPropertyDeclInfo_setter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXIdxEntityInfo(cPtr, false);
  }

  public CXIdxObjCPropertyDeclInfo() {
    this(clangjavaJNI.new_CXIdxObjCPropertyDeclInfo(), true);
  }

}
