/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXIndexOptFlags {
  CXIndexOpt_None(0x0),
  CXIndexOpt_SuppressRedundantRefs(0x1),
  CXIndexOpt_IndexFunctionLocalSymbols(0x2),
  CXIndexOpt_IndexImplicitTemplateInstantiations(0x4),
  CXIndexOpt_SuppressWarnings(0x8),
  CXIndexOpt_SkipParsedBodiesInSession(0x10);

  public final int swigValue() {
    return swigValue;
  }

  public static CXIndexOptFlags swigToEnum(int swigValue) {
    CXIndexOptFlags[] swigValues = CXIndexOptFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXIndexOptFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXIndexOptFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXIndexOptFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXIndexOptFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXIndexOptFlags(CXIndexOptFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

