/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXLanguageKind {
  CXLanguage_Invalid(0),
  CXLanguage_C,
  CXLanguage_ObjC,
  CXLanguage_CPlusPlus;

  public final int swigValue() {
    return swigValue;
  }

  public static CXLanguageKind swigToEnum(int swigValue) {
    CXLanguageKind[] swigValues = CXLanguageKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXLanguageKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXLanguageKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXLanguageKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXLanguageKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXLanguageKind(CXLanguageKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

