/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXNameRefFlags {
  CXNameRange_WantQualifier(0x1),
  CXNameRange_WantTemplateArgs(0x2),
  CXNameRange_WantSinglePiece(0x4);

  public final int swigValue() {
    return swigValue;
  }

  public static CXNameRefFlags swigToEnum(int swigValue) {
    CXNameRefFlags[] swigValues = CXNameRefFlags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXNameRefFlags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXNameRefFlags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXNameRefFlags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXNameRefFlags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXNameRefFlags(CXNameRefFlags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

