/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXObjCDeclQualifierKind {
  CXObjCDeclQualifier_None(0x0),
  CXObjCDeclQualifier_In(0x1),
  CXObjCDeclQualifier_Inout(0x2),
  CXObjCDeclQualifier_Out(0x4),
  CXObjCDeclQualifier_Bycopy(0x8),
  CXObjCDeclQualifier_Byref(0x10),
  CXObjCDeclQualifier_Oneway(0x20);

  public final int swigValue() {
    return swigValue;
  }

  public static CXObjCDeclQualifierKind swigToEnum(int swigValue) {
    CXObjCDeclQualifierKind[] swigValues = CXObjCDeclQualifierKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXObjCDeclQualifierKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXObjCDeclQualifierKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXObjCDeclQualifierKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXObjCDeclQualifierKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXObjCDeclQualifierKind(CXObjCDeclQualifierKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

