/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXPlatformAvailability {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXPlatformAvailability(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXPlatformAvailability obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXPlatformAvailability(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlatform(CXString value) {
    clangjavaJNI.CXPlatformAvailability_Platform_set(swigCPtr, this, CXString.getCPtr(value), value);
  }

  public CXString getPlatform() {
    long cPtr = clangjavaJNI.CXPlatformAvailability_Platform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXString(cPtr, false);
  }

  public void setIntroduced(CXVersion value) {
    clangjavaJNI.CXPlatformAvailability_Introduced_set(swigCPtr, this, CXVersion.getCPtr(value), value);
  }

  public CXVersion getIntroduced() {
    long cPtr = clangjavaJNI.CXPlatformAvailability_Introduced_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXVersion(cPtr, false);
  }

  public void setDeprecated(CXVersion value) {
    clangjavaJNI.CXPlatformAvailability_Deprecated_set(swigCPtr, this, CXVersion.getCPtr(value), value);
  }

  public CXVersion getDeprecated() {
    long cPtr = clangjavaJNI.CXPlatformAvailability_Deprecated_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXVersion(cPtr, false);
  }

  public void setObsoleted(CXVersion value) {
    clangjavaJNI.CXPlatformAvailability_Obsoleted_set(swigCPtr, this, CXVersion.getCPtr(value), value);
  }

  public CXVersion getObsoleted() {
    long cPtr = clangjavaJNI.CXPlatformAvailability_Obsoleted_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXVersion(cPtr, false);
  }

  public void setUnavailable(int value) {
    clangjavaJNI.CXPlatformAvailability_Unavailable_set(swigCPtr, this, value);
  }

  public int getUnavailable() {
    return clangjavaJNI.CXPlatformAvailability_Unavailable_get(swigCPtr, this);
  }

  public void setMessage(CXString value) {
    clangjavaJNI.CXPlatformAvailability_Message_set(swigCPtr, this, CXString.getCPtr(value), value);
  }

  public CXString getMessage() {
    long cPtr = clangjavaJNI.CXPlatformAvailability_Message_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXString(cPtr, false);
  }

  public CXPlatformAvailability() {
    this(clangjavaJNI.new_CXPlatformAvailability(), true);
  }

}
