/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXResult {
  CXResult_Success(0),
  CXResult_Invalid(1),
  CXResult_VisitBreak(2);

  public final int swigValue() {
    return swigValue;
  }

  public static CXResult swigToEnum(int swigValue) {
    CXResult[] swigValues = CXResult.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXResult swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXResult.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXResult() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXResult(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXResult(CXResult swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

