/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXRefQualifierKind {
  CXRefQualifier_None(0),
  CXRefQualifier_LValue,
  CXRefQualifier_RValue;

  public final int swigValue() {
    return swigValue;
  }

  public static CXRefQualifierKind swigToEnum(int swigValue) {
    CXRefQualifierKind[] swigValues = CXRefQualifierKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXRefQualifierKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXRefQualifierKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXRefQualifierKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXRefQualifierKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXRefQualifierKind(CXRefQualifierKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

