/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXSaveError {
  CXSaveError_None(0),
  CXSaveError_Unknown(1),
  CXSaveError_TranslationErrors(2),
  CXSaveError_InvalidTU(3);

  public final int swigValue() {
    return swigValue;
  }

  public static CXSaveError swigToEnum(int swigValue) {
    CXSaveError[] swigValues = CXSaveError.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXSaveError swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXSaveError.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXSaveError() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXSaveError(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXSaveError(CXSaveError swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

