/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXTranslationUnit_Flags {
  CXTranslationUnit_None(0x0),
  CXTranslationUnit_DetailedPreprocessingRecord(0x01),
  CXTranslationUnit_Incomplete(0x02),
  CXTranslationUnit_PrecompiledPreamble(0x04),
  CXTranslationUnit_CacheCompletionResults(0x08),
  CXTranslationUnit_ForSerialization(0x10),
  CXTranslationUnit_CXXChainedPCH(0x20),
  CXTranslationUnit_SkipFunctionBodies(0x40),
  CXTranslationUnit_IncludeBriefCommentsInCodeCompletion(0x80);

  public final int swigValue() {
    return swigValue;
  }

  public static CXTranslationUnit_Flags swigToEnum(int swigValue) {
    CXTranslationUnit_Flags[] swigValues = CXTranslationUnit_Flags.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXTranslationUnit_Flags swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXTranslationUnit_Flags.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXTranslationUnit_Flags() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXTranslationUnit_Flags(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXTranslationUnit_Flags(CXTranslationUnit_Flags swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

