/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXTUResourceUsage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXTUResourceUsage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXTUResourceUsage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXTUResourceUsage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    clangjavaJNI.CXTUResourceUsage_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = clangjavaJNI.CXTUResourceUsage_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setNumEntries(long value) {
    clangjavaJNI.CXTUResourceUsage_numEntries_set(swigCPtr, this, value);
  }

  public long getNumEntries() {
    return clangjavaJNI.CXTUResourceUsage_numEntries_get(swigCPtr, this);
  }

  public void setEntries(CXTUResourceUsageEntry value) {
    clangjavaJNI.CXTUResourceUsage_entries_set(swigCPtr, this, CXTUResourceUsageEntry.getCPtr(value), value);
  }

  public CXTUResourceUsageEntry getEntries() {
    long cPtr = clangjavaJNI.CXTUResourceUsage_entries_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CXTUResourceUsageEntry(cPtr, false);
  }

  public CXTUResourceUsage() {
    this(clangjavaJNI.new_CXTUResourceUsage(), true);
  }

}
