/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public enum CXTypeLayoutError {
  CXTypeLayoutError_Invalid(-1),
  CXTypeLayoutError_Incomplete(-2),
  CXTypeLayoutError_Dependent(-3),
  CXTypeLayoutError_NotConstantSize(-4),
  CXTypeLayoutError_InvalidFieldName(-5);

  public final int swigValue() {
    return swigValue;
  }

  public static CXTypeLayoutError swigToEnum(int swigValue) {
    CXTypeLayoutError[] swigValues = CXTypeLayoutError.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CXTypeLayoutError swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CXTypeLayoutError.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CXTypeLayoutError() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CXTypeLayoutError(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CXTypeLayoutError(CXTypeLayoutError swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

