/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class CXVersion {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CXVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CXVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_CXVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMajor(int value) {
    clangjavaJNI.CXVersion_Major_set(swigCPtr, this, value);
  }

  public int getMajor() {
    return clangjavaJNI.CXVersion_Major_get(swigCPtr, this);
  }

  public void setMinor(int value) {
    clangjavaJNI.CXVersion_Minor_set(swigCPtr, this, value);
  }

  public int getMinor() {
    return clangjavaJNI.CXVersion_Minor_get(swigCPtr, this);
  }

  public void setSubminor(int value) {
    clangjavaJNI.CXVersion_Subminor_set(swigCPtr, this, value);
  }

  public int getSubminor() {
    return clangjavaJNI.CXVersion_Subminor_get(swigCPtr, this);
  }

  public CXVersion() {
    this(clangjavaJNI.new_CXVersion(), true);
  }

}
