/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class IndexerCallbacks {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IndexerCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexerCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clangjavaJNI.delete_IndexerCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAbortQuery(SWIGTYPE_p_f_p_void_p_void__int value) {
    clangjavaJNI.IndexerCallbacks_abortQuery_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__int getAbortQuery() {
    long cPtr = clangjavaJNI.IndexerCallbacks_abortQuery_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__int(cPtr, false);
  }

  public void setDiagnostic(SWIGTYPE_p_f_p_void_p_void_p_void__void value) {
    clangjavaJNI.IndexerCallbacks_diagnostic_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void_p_void__void getDiagnostic() {
    long cPtr = clangjavaJNI.IndexerCallbacks_diagnostic_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void_p_void__void(cPtr, false);
  }

  public void setEnteredMainFile(SWIGTYPE_p_f_p_void_p_void_p_void__p_void value) {
    clangjavaJNI.IndexerCallbacks_enteredMainFile_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void_p_void__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void_p_void__p_void getEnteredMainFile() {
    long cPtr = clangjavaJNI.IndexerCallbacks_enteredMainFile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void_p_void__p_void(cPtr, false);
  }

  public void setPpIncludedFile(SWIGTYPE_p_f_p_void_p_q_const__CXIdxIncludedFileInfo__p_void value) {
    clangjavaJNI.IndexerCallbacks_ppIncludedFile_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__CXIdxIncludedFileInfo__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__CXIdxIncludedFileInfo__p_void getPpIncludedFile() {
    long cPtr = clangjavaJNI.IndexerCallbacks_ppIncludedFile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__CXIdxIncludedFileInfo__p_void(cPtr, false);
  }

  public void setImportedASTFile(SWIGTYPE_p_f_p_void_p_q_const__CXIdxImportedASTFileInfo__p_void value) {
    clangjavaJNI.IndexerCallbacks_importedASTFile_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__CXIdxImportedASTFileInfo__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__CXIdxImportedASTFileInfo__p_void getImportedASTFile() {
    long cPtr = clangjavaJNI.IndexerCallbacks_importedASTFile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__CXIdxImportedASTFileInfo__p_void(cPtr, false);
  }

  public void setStartedTranslationUnit(SWIGTYPE_p_f_p_void_p_void__p_void value) {
    clangjavaJNI.IndexerCallbacks_startedTranslationUnit_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__p_void getStartedTranslationUnit() {
    long cPtr = clangjavaJNI.IndexerCallbacks_startedTranslationUnit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__p_void(cPtr, false);
  }

  public void setIndexDeclaration(SWIGTYPE_p_f_p_void_p_q_const__CXIdxDeclInfo__void value) {
    clangjavaJNI.IndexerCallbacks_indexDeclaration_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__CXIdxDeclInfo__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__CXIdxDeclInfo__void getIndexDeclaration() {
    long cPtr = clangjavaJNI.IndexerCallbacks_indexDeclaration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__CXIdxDeclInfo__void(cPtr, false);
  }

  public void setIndexEntityReference(SWIGTYPE_p_f_p_void_p_q_const__CXIdxEntityRefInfo__void value) {
    clangjavaJNI.IndexerCallbacks_indexEntityReference_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__CXIdxEntityRefInfo__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__CXIdxEntityRefInfo__void getIndexEntityReference() {
    long cPtr = clangjavaJNI.IndexerCallbacks_indexEntityReference_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__CXIdxEntityRefInfo__void(cPtr, false);
  }

  public IndexerCallbacks() {
    this(clangjavaJNI.new_IndexerCallbacks(), true);
  }

}
