/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package st.bug.clang.swig;

public class SWIGTYPE_p_CXLoadDiag_Error {
  private long swigCPtr;

  protected SWIGTYPE_p_CXLoadDiag_Error(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_CXLoadDiag_Error() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_CXLoadDiag_Error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

